cohesion_elements.cohesion_component_tag.*:
  type: cohesion_config_entity
  label: 'Component tag configuration'
  mapping:
    class:
      type: string
      label: 'Class'
    weight:
      type: integer
      label: 'Weight'
