<?php

/**
 * @file
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cohesion_style_helpers_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cohesion_style_helpers module.
    case 'help.page.cohesion_style_helpers':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module defines the style helper entity for creating reusable styles in Site Studio.') . '</p>';
      $output .= '<p><ul>';
      $output .= '  <li>Style helper configuration entity and supporting forms.</li>';
      $output .= '</ul></p>';
      $output .= '<p><a href="https://sitestudiodocs.acquia.com/" target="_blank">https://sitestudiodocs.acquia.com/</a></p>';
      return $output;

    default:
  }
}
