<?php

namespace Drupal\cohesion\Entity;

use Drupal\Core\Config\Entity\ConfigEntityInterface;

/**
 * Provides an interface for defining Site Studio configuration entities.
 *
 * Interface CohesionSettingsInterface.
 *
 * @package Drupal\cohesion\Entity
 */
interface CohesionSettingsInterface extends ConfigEntityInterface, EntityJsonValuesInterface {

  /**
   * Reset the entity to its default state.
   *
   * @throws \Drupal\Core\Entity\EntityStorageException
   *   In case of failures an exception is thrown.
   */
  public function reset();

  /**
   * Clear any data generated by Site Studio like template files, css.
   */
  public function clearData();

  /**
   * Set all entity properties to their defaults (i.e. blank).
   */
  public function setDefaultValues();

  /**
   * Return whether entity has in use tracking.
   *
   * @return bool
   */
  public function hasInUse();

  /**
   * Get the markup for in use.
   *
   * @return mixed|null
   *
   * @throws \Drupal\Core\Entity\EntityMalformedException
   */
  public function getInUseMarkup();

  /**
   * Return the message to display for the in use modal as a render array.
   *
   * @return array
   */
  public function getInUseMessage();

  /**
   * Return the machine name prefix for this entity.
   *
   * @return mixed
   */
  public function getEntityMachineNamePrefix();

  /**
   * Can the user edit the machine? (Is it new, a duplicate or not in use?)
   *
   * @return bool
   */
  public function canEditMachineName();

  /**
   * Can the entity be overriden by sync?
   *
   * @return array
   */
  public function isLocked();

  /**
   * Set whether the entity can be overridden by Sync.
   *
   * @param $locked
   *
   * @return $this
   */
  public function setLocked($locked);

}
