cohesion.sync.settings:
  type: config_object
  mapping:
    enabled_entity_types:
      type: sequence
      sequence:
        type: string
    package_export_limit:
      type: integer
    full_export_limit:
      type: integer
